packages:
  - "apps/*"
  - "packages/*"
overrides:
  "@expo/metro-runtime": 57.0.3
  expo-constants: 57.0.3
  expo-file-system: 57.0.0
  react-native: 0.86.0
onlyBuiltDependencies:
  - msgpackr-extract
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - expo-modules-autolinking@57.0.4
  - expo@57.0.2
